version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - GITHUB_SHA=${GITHUB_SHA}
    container_name: pr${PR_NUMBER}_fast_app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - ./backend/.env
    environment:
      VITE_API_URL: http://${EC2_HOST}:${BACKEND_PORT:-8000}
      PR_NUMBER: ${PR_NUMBER}
      GITHUB_SHA: ${GITHUB_SHA}

  frontend:
    build:
      context: ./frontend
      args:
        - GITHUB_SHA=${GITHUB_SHA}
    container_name: pr${PR_NUMBER}_node_app
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_URL: http://${EC2_HOST}:${BACKEND_PORT:-8000}
      PR_NUMBER: ${PR_NUMBER}
      GITHUB_SHA: ${GITHUB_SHA}

volumes:
  pr${PR_NUMBER}_postgres_data:

networks:
  pr${PR_NUMBER}_network:
    name: pr${PR_NUMBER}_network